# Generated by Django 6.0 on 2025-12-09 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailplan',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.mailnode')),
            ],
        ),
    ]
